import {create} from 'zustand';

const initialState = {
  patient:'',
  doctor:'',
  prodTotal:0,
  servTotal:0,
  variationsTotal:0,
  total: 0,
  procedure:'',
  notes:'',
  servVariations:[],
  problems:[],
  servList:[],
  prodList:[],
  prices:[],
  qties:[],
};
export const useRecordState = create((set) => ({
  patient:'',
  doctor:'',
  procedure:'',
  notes:'',
  servTotal: 0,
  variationsTotal: 0,
  prodTotal: 0,
  total: () => {
    return servTotal + variationsTotal + prodTotal
  },
  servVariations: [],
  problems:[],
  servList:[],
  prodList:[],
  prices:[],
  qties:[],
  setPatient: (patient) => set({patient}),
  setDoctor: (doctor) => set({doctor}),
  setServVariations: (servVariations) => set({servVariations}),
  setProdTotal: (prodTotal) => set({prodTotal}),
  setServTotal: (servTotal) => set({servTotal}),
  setProblems: (problems) => set({problems}),
  setServList: (servList) => set({servList}),
  setProdList: (prodList) => set({prodList}),
  setProcedure: (procedure) => set({procedure}),
  setNotes: (notes) => set({notes}),
  setPrices: (prices) => set({prices}),
  setQties: (qties) => set({qties}),
  reset: () => set(initialState),
}));
