import {create} from 'zustand'
import { serverTimestamp } from 'firebase/firestore';

const initialState = {
  selectedPatient:'',
  doctor:'',
  date: new Date(),
  prodTotal:0,
  servTotal:0,
  variationsTotal:0,
  procedure:'',
  notes:'',
  servVariations:[],
  problems:[],
  servList:[],
  prodList:[],
  prices:[],
  qties:[],
};
export const useRecordState = create((set, get) => ({
  patient:'',
  doctor:'',
  procedure:'',
  notes:'',
  date: new Date(),
  nextDate: '',
  nextService: '',
  servTotal: 0,
  variationsTotal: 0,
  servVariations: [],
  prodTotal: 0,
  total: () => {
    const { servTotal, variationsTotal, prodTotal } = get();
    return servTotal + variationsTotal + prodTotal;
  },
  problems:[],
  servList:[],
  prodList:[],
  prices:[],
  qties:[],
  setSelectedPatient: (selectedPatient) => set({selectedPatient}),
  setDoctor: (doctor) => set({doctor}),
  setServVariations: (servVariations) => set({ servVariations }),
  setDate: (date) => set({date}),
  setNextDate: (nextDate) => set({nextDate}),
  setNextService: (nextService) => set({nextService}),
  setProdTotal: (prodTotal) => set({prodTotal}),
  setServTotal: (servTotal) => set({servTotal}),
  setVariationsTotal: (variationsTotal) => set({variationsTotal}),
  setProblems: (problems) => set({problems}),
  setServList: (servList) => set({servList}),
  setProdList: (prodList) => set({prodList}),
  setProcedure: (procedure) => set({procedure}),
  setNotes: (notes) => set({notes}),
  setPrices: (prices) => set({prices}),
  setQties: (qties) => set({qties}),
  reset: () => set(initialState),
}));
